### ISSUE TITLE
timeout error since Hoobs 3.3.7 and/or plugin 1.1.1

### ISSUE THREAD

**Issue by Thomasgotschi** [laundrify/homebridge-laundrify-official#2]
Since update to hoobs 3.3.7 there is a timeout error

```
10.7.2021, 09:10:24 [laundrify] Error while polling Machine status:  {
  message: 'timeout of 2500ms exceeded',
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: timeout of 2500ms exceeded\n' +
    '    at createError (/home/hoobs/.hoobs/node_modules/axios/lib/core/createError.js:16:15)\n' +
    '    at RedirectableRequest.handleRequestTimeout (/home/hoobs/.hoobs/node_modules/axios/lib/adapters/http.js:280:16)\n' +
    '    at RedirectableRequest.emit (events.js:315:20)\n' +
    '    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/follow-redirects/index.js:166:12)\n' +
    '    at listOnTimeout (internal/timers.js:554:17)\n' +
    '    at processTimers (internal/timers.js:497:7)',
  config: {
    url: '/api/machines/2fa90672',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: '...',
      'User-Agent': 'axios/0.21.1'
    },
    baseURL: 'https://api.laundrify.de',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 2500,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  code: 'ECONNABORTED':
```

**Environment:**

* **Plugin Version 1.1.1**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by xLarry** [comment]
Thanks for your report, @Thomasgotschi.

Indeed, in [v1.1.1](https://github.com/laundrify/homebridge-laundrify-official/blob/master/CHANGELOG.md#v111-2021-07-02) a timeout has been added to the request that polls the current status. The timeout value of 2.5s seems to be a bit too restrictive.

I am currently running some tests to figure out a more suitable value and publish a new release (will most likely settle at around 5s).

**Comment by Thomasgotschi** [comment]
some news ?

**Comment by xLarry** [comment]
It turned out that requests seems to be "stuck" occasionally and thus resulting in a timeout (no matter which timeout value being used). The issue seems to be caused by the backend, but I couldn't figure out the actual bottleneck yet.

However I implemented a mechanism to resend the request if it fails (max 3 times with exponential backoff). This doesn't solve the actual issue but might increase the chance for the request to succeed.

Need to test it for some more time, but would be happy to receive your feedback after releasing the update.

**UPDATE**: just released v1.2.0 with the above mentioned change. Please note that the issue still _might_ occur, hopefully less frequently than before. Looking forward to your feedback.

**Comment by Thomasgotschi** [comment]
I'll install the update and you'll get a feedback

**Comment by Thomasgotschi** [comment]
![hoobs](https://user-images.githubusercontent.com/87224266/128849171-d4459402-2647-4635-b650-c6d47bd09e29.jpg)

unfortunately the bridge crashes some times. After today's crash I made a screen shot and attached it

**Comment by Thomasgotschi** [comment]
hoobs chrashed again. I´ve removed the plugin now.

![hoobs](https://user-images.githubusercontent.com/87224266/128870479-98d4c84a-d230-4b27-a991-906ee8b11f36.jpg)

**Comment by Thomasgotschi** [comment]
In the meantime i was forced to use a backup. Unfortuneality the plugin-Version 1.1.1 is included in the backup. Is it possible to get the older version?

**Comment by xLarry** [comment]
To install an older version of the plugin, use the following (as documented [here](https://docs.npmjs.com/cli/v7/commands/npm-install)):

```sh
npm i homebridge-laundrify-official@1.1.0
```

Please note that the timeout errors are caused by the backend (as mentioned in my last comment). I don't expect that an older plugin version will solve the problem.

**Comment by Thomasgotschi** [comment]
Whatever, i removed the plugin now and work with the app

it was not possible (for me) so install the older version of the plugin on the Hoobs-System via Terminal. I close this issue now.
